version: "3.8"
services:
  db:
    image: postgres:13
    ports:
      - "127.0.0.1:39652:5432/tcp"
    container_name: terrygon_postgres
    environment:
      POSTGRES_USER: terrygon
      POSTGRES_PASSWORD: spacecore
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U terrygon"]
      interval: 10s
      timeout: 5s
      retries: 5

  terrygon:
    build: .
    container_name: terrygon
    volumes:
      - ./data:/opt/terrygon/data/
    depends_on:
      db:
        condition: service_healthy

    #restart: always
